### ISSUE TITLE
Can not install The Camera Package while using the Camera ML Package 

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#12]
Whenever i install the camera package there is an error occurs related to the Camera ML Package:

Because flutter_camera_ml_vision 1.2.0 depends on camera from git and no versions of flutter_camera_ml_vision match >1.2.0 <2.0.0, flutter_camera_ml_vision ^1.2.0 requires camera from git.

So, because looper_2019 depends on both flutter_camera_ml_vision ^1.2.0 and camera from hosted, version solving failed.
pub get failed (1)
exit code 1

**Comment by jaumard** [comment]
The flutter_camera_ml_vision is using the camera package, so you can't add it again as the error message said, but you should be able to use it a transitive dependency :) until the PR made to camera plugin is merge, we can't used a specific version and have to use the git hosted version

**Comment by Loopex2019** [comment]
Thanks for your answer but what do you mean with transitive dependency

**Comment by jaumard** [comment]
I mean you don't need to add it on your pubspec.yaml at all, or if you want to have you need to put it under dependency_overrides with 
```
camera: 
    git:
      url: git@github.com:jaumard/plugins.git
      ref: feature/camera_api_16_installation
      path: packages/camera
```

**Comment by Loopex2019** [comment]
Okay thanks for that I will try soon

**Comment by Loopex2019** [comment]
Hi there. Where is that : dependency_overrides in pupspec.yaml file to add the camera extension?

**Comment by jaumard** [comment]
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides :)

**Comment by Loopex2019** [comment]
I tried it but there is an another Error occurs  to me /
 Running "flutter packages get" in looper_2019...                

Git error. Command: git rev-list --max-count=1 feature/camera_api_16_installation

fatal: ambiguous argument 'feature/camera_api_16_installation': unknown revision or path not in the working tree.

And this the code i have written
![image](https://user-images.githubusercontent.com/49901727/56892176-19ef1300-6a7f-11e9-9506-62b1cbcd6df9.png)

And the Error is here
![image](https://user-images.githubusercontent.com/49901727/56892227-460a9400-6a7f-11e9-8613-668d351507c9.png)

**Comment by jaumard** [comment]
Ho maybe you need the https url version:
```
camera: 
    git:
      url: https://github.com/jaumard/plugins.git
      ref: feature/camera_api_16_installation
      path: packages/camera
```
Try it might be better
